blog/urls.py
from django.urls import path

from blog.views import(
	create_blog_view,
	detail_blog_view,
	edit_blog_view,
	delete_blog_view,
	)

app_name = 'blog'

urlpatterns = [
	path('create', create_blog_view, name='create'),
	path('<slug>/', detail_blog_view, name='detail'),
	path('<slug>/edit', edit_blog_view, name='edit'),
	path('<slug>/delete',delete_blog_view, name='delete'),

]

mainFolder/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views



from index.views import(
		home_screen_view,
		info_screen_view,
		info_screen_two_view,
	)

from accounts.views import(
	registration_view,
	logout_view,
	login_view,
    must_authenticate_view,
    account_view,
    must_be_a_admin,
	)

urlpatterns = [

	path('admin/', admin.site.urls),

	path('account/',account_view,name='account'),  
	path('login/',login_view,name='login'),
	path('register/',registration_view,name='register'),
	path('logout/',logout_view,name='logout'),
	path('must_authenticate/',must_authenticate_view,name='must_authenticate'),
	path('must_be_a_admin/',must_be_a_admin,name='must_be_a_admin'),

	path('blog/',include('blog.urls','blog')),
	
	path('accounts/', include('allauth.urls')),

	path('',home_screen_view,name='home'),
	path('info/',info_screen_view,name='info'),
	path('info2/',info_screen_two_view,name='info2'),

	# Password reset links (ref: https://github.com/django/django/blob/master/django/contrib/auth/views.py)
	path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'), 
		name='password_change_done'),

	path('password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'), 
		name='password_change'),

	path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'),
		name='password_reset_done'),

	path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),

	path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),

	path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
		name='password_reset_complete'),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
  

templates/snippes/account_change_css.html
<style type="text/css">
    /* Head */
    .acc-col{


      min-height: 300px;
      margin-top: 5%;
      background-color: #ffffff;
      padding: 20px;

    }
    .acc-col > h3{
      padding-bottom: 20px;
    }
    hr{
      border:solid 1px #d6d6d6;
    }
    section > form > div{

      padding: 5px;
    }
    .btn-div{

      margin-top:10px;
      padding-bottom: 10px;
    }

    
.ui-67 .ui-head{
  text-align:center;
  padding:30px 0px;
  position:relative;
  border-bottom:2px solid #fff;
  box-shadow:0px 0px 5px rgba(0,0,0,0.1);
  background-color: #1997c6;
}
/* Details */
.ui-67 .ui-head .ui-details{
  margin:0px 0px 74px;
}
.ui-67 .ui-head .ui-details h3{
  color:#fff;
  font-size:40px;
  line-height:60px;
  font-weight:300;
}
@media (max-width:400px){
  .ui-67 .ui-head .ui-details h3{
    font-size:25px;
    line-height:40px;
    font-weight:400;
  }
}
.ui-67 .ui-head .ui-details h4{
  color:#fff;
  font-size:18px;
  line-height:38px; 
  font-weight:400;
}
/* Image */
.ui-67 .ui-head .ui-image{
  width:100%;
  position:absolute;
  bottom:-55px;
  z-index: 10;
}
.ui-67 .ui-head img{
  width:120px;
  height: 130px;
  border-radius:100%;
  margin:0px auto;
  border:4px solid #fff;
  box-shadow:0px 0px 15px rgba(0,0,0,0.1);
}

</style>

templates/snippes/base_css.html
{% load static %}
<style type="text/css">
  
@import url(https://fonts.googleapis.com/css?family=Montserrat);

body{
  background: #030321;
}
svg {
    display: block;
    font: 10.5em 'Montserrat';
    width: 1000px;
    height: 500px;
    margin: 0 auto;
}

.text-copy {
    fill: none;
    stroke: white;
    stroke-dasharray: 6% 29%;
    stroke-width: 5px;
    stroke-dashoffset: 0%;
    animation: stroke-offset 5.5s infinite linear;
}

.text-copy:nth-child(1){
    stroke: #4D163D;
	animation-delay: -1;
}

.text-copy:nth-child(2){
	stroke: #840037;
	animation-delay: -2s;
}

.text-copy:nth-child(3){
	stroke: #BD0034;
	animation-delay: -3s;
}

.text-copy:nth-child(4){
	stroke: #BD0034;
	animation-delay: -4s;
}

.text-copy:nth-child(5){
	stroke: #FDB731;
	animation-delay: -5s;
}

@keyframes stroke-offset{
	100% {stroke-dashoffset: -35%;}
}
.header {
  position: relative;
  width: 100vw;	
  height: 600px;	
}
.header .center {
	position: absolute;
	top: 50%;
	left: 50%;
	width: 90%;
	transform:translate(-50%,-50%);
	z-index: 5; 
  padding: 1rem;
}
.header .left {
  position: absolute;
	top: 50%;
	left: 50%;
	width: 90%;
	transform:translate(-50%,-50%);
	z-index: 5; 
  padding: 1rem;
}
.header .right {
  position: absolute;
	top: 50%;
	left: 50%;
	width: 90%;
	transform:translate(-50%,-50%);
	z-index: 5; 
  padding: 1rem;
}
.header .scroll {
  position: absolute;
  top: 95%;
  left: 50%;
  transform:translate(-50%,-50%);
  color: #fff;
  font-size: 1.5rem;
}
/*=== Large devices (desktops, 992px and up) ===*/
@media (min-width: 992px) {
.header .center {
  width: 50%;
}
.header .left {
  position: absolute;
  top: 20%;
  left: 10%;
  width: 40%;
  height: 60%;
  transform:translate(0, 0);
  padding: 1rem;
}
.header .right {
  position: absolute;
  top: 20%;
  left: 50%;
  width: 40%;
  height: 60%;
  transform:translate(0, 0);
  padding: 1rem;
}
.delay {
  animation-delay: 0.6s;
}
}

/* =======================================
 header#1
========================================*/
#header1 {
	background: #355c7d;
  background:
    /* gradient overlay */
    linear-gradient(
      to bottom,
      rgba(203, 53, 107, 0.6), /* #cb356b */
      rgba(189, 63, 50, 0.5) /* #bd3f32 */
    ),
    /* bottom image */
  no-repeat left top;
  background-size: cover;  
	z-index: 0; 
}
#header1 .caption {
	text-align: center;
  color: #fff;
}
#header1 .caption .title {
	margin-bottom: 1.5rem;
} 
#header1 .caption .text {
	margin-bottom: 1.5rem;
}
#header1 .caption .action {
	margin-bottom: 1rem;
	padding-left: 3rem;
	padding-right: 3rem;
	border-radius: 15px;
}
  
/* =======================================
 header#3
========================================*/
#header3 {
	background: #355c7d;  
  background: 
    linear-gradient(
      to left,
      rgba(214, 109, 117, 0.8), /* #d66d75 */
      rgba(226, 149, 135, 0.7) /* #e29587 */
    ),
  url(https://hdqwalls.com/download/material-design-4k-2048x1152.jpg) no-repeat left top;  
  background-size: cover;  
	z-index: 0; /* bottom layout */
}
#header3 .right {
	display: none;
}
#header3 .caption {
	z-index: 5; 
  text-align: center;
  color: #fff;
}
#header3 .caption .title {
	margin-bottom: 1.5rem;
} 
#header3 .caption .text {
	margin-bottom: 1.5rem;
} 
#header3 .caption .action {
	margin-bottom: 1rem;
	padding-left: 3rem;
	padding-right: 3rem;
}
/*=== Large devices (desktops, 992px and up) ===*/
@media (min-width: 992px) {
#header3 .caption {
  text-align: left;
}
#header3 .right {
  display: block;
}
}

/* =======================================
 header#4
========================================*/
#header4 {
	background: #355c7d;  
  background:
    linear-gradient(
      rgba(53, 92, 125, 0.8), /* #355c7d */
      rgba(108, 91, 123, 0.8), /* #6c5b7b */
      rgba(192, 108, 123, 0.8) /* #c06c7b */
    ),

  url(https://hdqwalls.com/download/material-design-4k-2048x1152.jpg) no-repeat left top;
  background-size: cover;  
	z-index: 0; /* bottom layout */
}
#header4 .caption {
	z-index: 5; 
  text-align: center;
  color: #fff;
}
#header4 .caption .title {
	margin-bottom: 1.5rem;
}
#header4 .caption .text {
	margin-bottom: 1.5rem;
}
#header4 .caption .action {
  display: flex;
  margin-bottom: 1rem;
  margin-left: 15%;
  width: 70%;
}
/*=== Large devices (desktops, 992px and up) ===*/
@media (min-width: 992px) {
#header4 .caption .action {
  margin-left: 10%;
  width: 80%;
}
}

/* =======================================
 header#5
========================================*/
#header5 {
	background: #355c7d; 
	background: linear-gradient(to right, #4ac29a, #bdfff3);
  z-index: 0; 
  overflow: hidden;
}
#header5 .right {
  display: none;
}
#header5 .opacity-text {
  position: absolute;
  left: 75%;
  top: 15%;
  transform: translate(-50%, -50%);
  font-size: 10rem;
  font-weight: 900;
  columns: #fff;
  opacity: 0.1;
  transform: rotate(90deg);
}
#header5 .caption {
	z-index: 5; 
  text-align: center;
  color: #fff;
}
#header5 .caption .title {
	margin-bottom: 1.5rem;
} 
#header5 .caption .text {
	margin-bottom: 1.5rem;
} 
#header5 .caption .action {
	margin-bottom: 1rem;
	padding-left: 3rem;
	padding-right: 3rem;
	border-radius: 10px;
}
/*=== Large devices (desktops, 992px and up) ===*/
@media (min-width: 992px) {
#header5 .right {
  display: block;
}

#header5 .caption {
  text-align: right;
}
}
 
/* =======================================
demo css
========================================*/

/*=== for demo only ===*/
.demo-title {
  text-align: center;
  color: #808080;
  padding-top: 20vh;
  padding-bottom: 20vh;
}
.demo-more {
  text-align: center;
  color: #808080;
  padding-top: 10vh;
  padding-bottom: 10vh;
}
.demo-more i {
  color: #696969;
}
.update-note {
  position: absolute;
  top: 2%;
  left: 2%;
  background-color: rgb(33, 33, 33);
  color: #fff;
  border-radius: 10px;
  padding: 0 15px;  
}
a {
  text-decoration: underline;
  color: #696969;
  font-weight: 600;
}
a:hover {
  color: #696969;
}
body {
  overflow-x: hidden;
}


</style>

templates/snippes/header.html
{% load static %}
  <!--Navbar -->

<nav class="navbar fixed-top navbar-expand-lg navbar-dark scrolling-navbar bg-primary">
  <a class="navbar-brand" href="/">Home</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      {% if request.user.is_authenticated %}
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true"
          aria-expanded="false">Profile 
        </a>
        <div class="dropdown-menu dropdown-primary" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="/account">My account</a>
          {% if request.user.is_admin %}
           <a class="dropdown-item" href="{% url 'blog:create' %}">Create blog</a>
           {% endif %}
          <a class="dropdown-item" href="{% url 'logout' %}">Log out</a>
        </div>
        
      </div>
      {% if '/info/' ==  request.path %}
       <form onsubmit="return executeQuery();">
            <input type="text" class="form-control" name="q" id="id_q" placeholder="Search for..." >
        </form>
        {% endif %}
      {% else %}
            </li>
      <li class="nav-item">
        <a class="nav-link" href="/register/">Registration</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/login/">Log in</a>
      </li>
    </ul>
    {% endif %}
  </div>
</nav>
  <!--/.Navbar -->
   
 {% if request.user.is_authenticated %}

<script type="text/javascript">
  document.getElementById("id_q").value = "{{query}}"
</script>
 {% endif %}
<script>
  function executeQuery() {
    var query = document.getElementById('id_q').value;
    window.location.replace("http://127.0.0.1:8000/info/?q=" + query)
    // "https://open-api.xyz/?q=" + query;
    return false
  }
</script>

templates/snippes/info2_css.html
<style type="text/css">
      .navbar {
    position: relative;
    min-height: 50px;
    margin-bottom: 20px;
    border: 1px solid transparent;
}
	.how-section1{
    margin-top:-15%;
    padding: 10%;
}
.how-section1 h4{
    color: #ffa500;
    font-weight: bold;
    font-size: 30px;
}
.how-section1 .subheading{
    color: #3931af;
    font-size: 20px;
}
.how-section1 .row
{
    margin-top: 10%;
}
.how-img 
{
    text-align: center;
}
.how-img img{
    width: 40%;
}
</style>

templates/snippes/info_css.html
<style type="text/css">
  /* FontAwesome for working BootSnippet :> */

@import url('https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css');
#team {
    background: #eee !important;
    position: relative;
}

.btn-primary:hover,
.btn-primary:focus {
    background-color: #108d6f;
    border-color: #108d6f;
    box-shadow: none;
    outline: none;
}

.btn-primary {
    color: #fff;
    background-color: #007b5e;
    border-color: #007b5e;
}

section {
    padding: 60px 0;
    position: relative;
  
}

section .section-title {
    text-align: center;
    color: #007b5e;
    margin-bottom: 50px;
    text-transform: uppercase;
}


.image-flip:hover .backside,
.image-flip.hover .backside {
    -webkit-transform: rotateY(0deg);
    -moz-transform: rotateY(0deg);
    -o-transform: rotateY(0deg);
    -ms-transform: rotateY(0deg);
    transform: rotateY(0deg);
    border-radius: .25rem;
}

.image-flip:hover .frontside,
.image-flip.hover .frontside {
    -webkit-transform: rotateY(180deg);
    -moz-transform: rotateY(180deg);
    -o-transform: rotateY(180deg);
    transform: rotateY(180deg);
}

.mainflip {
    -webkit-transition: 1s;
    -webkit-transform-style: preserve-3d;
    -ms-transition: 1s;
    -moz-transition: 1s;
    -moz-transform: perspective(1000px);
    -moz-transform-style: preserve-3d;
    -ms-transform-style: preserve-3d;
    transition: 1s;
    transform-style: preserve-3d;
    position: relative;
}

.frontside {
    position: relative;
    -webkit-transform: rotateY(0deg);
    -ms-transform: rotateY(0deg);
    z-index: 2;
    margin-bottom: 30px;
}

.backside {
    position: absolute;
    top: 0;
    left: 0;
    background: white;
    -webkit-transform: rotateY(-180deg);
    -moz-transform: rotateY(-180deg);
    -o-transform: rotateY(-180deg);
    -ms-transform: rotateY(-180deg);
    transform: rotateY(-180deg);
    -webkit-box-shadow: 5px 7px 9px -4px rgb(158, 158, 158);
    -moz-box-shadow: 5px 7px 9px -4px rgb(158, 158, 158);
    box-shadow: 5px 7px 9px -4px rgb(158, 158, 158);
}

.frontside,
.backside {
    -webkit-backface-visibility: hidden;
    -moz-backface-visibility: hidden;
    -ms-backface-visibility: hidden;
    backface-visibility: hidden;
    -webkit-transition: 1s;
    -webkit-transform-style: preserve-3d;
    -moz-transition: 1s;
    -moz-transform-style: preserve-3d;
    -o-transition: 1s;
    -o-transform-style: preserve-3d;
    -ms-transition: 1s;
    -ms-transform-style: preserve-3d;
    transition: 1s;
    transform-style: preserve-3d;
}

.frontside .card,
.backside .card {
    min-height: 312px;
}

.backside .card a {
    font-size: 18px;
    color: #007b5e !important;
}

.frontside .card .card-title,
.backside .card .card-title {
    color: #007b5e !important;
}

.frontside .card .card-body img {
    width: 120px;
    height: 120px;
    border-radius: 50%;
}
	.carousel-item {
  height: 100vh;
  min-height: 350px;
  background: no-repeat center center scroll;
  -webkit-background-size: cover;
  -moz-background-size: cover;
  -o-background-size: cover;
  background-size: cover;
}


.lnr {
  display: inline-block;
  fill: currentColor;
  width: 1em;
  height: 1em;
  vertical-align: -0.05em;
  stroke-width: 1;
}

.services-icon {
  margin-bottom: 20px;
  font-size: 30px;
}
bgc2, .vLine, .hLine {
    background-color: #0F52BA;
}

.services-icon {
    font-size: 60px;
    margin-left: 2rem;
}
</style>

templates/snippes/login_css.html
<style type="text/css">
	 body{
        padding-top:4.2rem;
		padding-bottom:4.2rem;
		background:rgba(0, 0, 0, 0.76);
        }
        a{
         text-decoration:none !important;
         }
         h1,h2,h3{
         font-family: 'Kaushan Script', cursive;
         }
          .myform{
		position: relative;
		display: -ms-flexbox;
		display: flex;
		padding: 1rem;
		-ms-flex-direction: column;
		flex-direction: column;
		width: 100%;
		pointer-events: auto;
		background-color: #fff;
		background-clip: padding-box;
		border: 1px solid rgba(0,0,0,.2);
		border-radius: 1.1rem;
		outline: 0;
		max-width: 500px;
		 }
         .tx-tfm{
         text-transform:uppercase;
         }
         .mybtn{
         border-radius:50px;
         }
        
         .login-or {
         position: relative;
         color: #aaa;
         margin-top: 10px;
         margin-bottom: 10px;
         padding-top: 10px;
         padding-bottom: 10px;
         }
         .span-or {
         display: block;
         position: absolute;
         left: 50%;
         top: -2px;
         margin-left: -25px;
         background-color: #fff;
         width: 50px;
         text-align: center;
         }
         .hr-or {
         height: 1px;
         margin-top: 0px !important;
         margin-bottom: 0px !important;
         }
         .google {
         color:#666;
         width:100%;
         height:40px;
         text-align:center;
         outline:none;
         border: 1px solid lightgrey;
         }
          form .error {
         color: #ff0000;
         }
         #second{display:none;}

</style>